# Generated by Django 6.0.1 on 2026-01-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categorie',
            field=models.CharField(choices=[('general', 'Général'), ('tech', 'Tech'), ('news', 'Actualités'), ('life', 'Lifestyle')], default='general', max_length=50),
        ),
    ]
