# Generated by Django 6.0.1 on 2026-01-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=255)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('whatsapp', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('pseudo_ou_entreprise', models.CharField(blank=True, max_length=128)),
                ('description_professionnelle', models.TextField(blank=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Profil propriétaire',
                'verbose_name_plural': 'Profil propriétaire',
            },
        ),
    ]
